import { BookOpenCheck, Link2 } from "lucide-react";
import type { AgentConversationTurn } from "../agentDemoTypes";

export function AgentReferencesPanel({ turn, selectedReferenceId, onSelectReference }: { turn?: AgentConversationTurn; selectedReferenceId: string | null; onSelectReference: (referenceId: string) => void }) {
  const objectById = new Map(turn?.relatedObjects.map((object) => [object.id, object]) ?? []);
  return (
    <section className="h-[218px] shrink-0 border-t border-slate-200 bg-white">
      <div className="flex h-11 items-center border-b border-slate-200 px-4"><BookOpenCheck className="h-4 w-4 text-slate-600" /><div className="ml-2 text-xs font-bold text-slate-900">References & Evidence</div><div className="ml-2 text-[9px] font-semibold text-slate-400">{turn ? `Turn ${turn.order} · ${turn.references.length} governed sources` : "Select a turn to inspect its evidence"}</div><div className="ml-auto rounded-full border border-emerald-100 bg-emerald-50 px-2.5 py-1 text-[8px] font-bold text-emerald-700">Claims remain linked to their source turn</div></div>
      {!turn ? <div className="flex h-[174px] items-center justify-center text-[10px] font-semibold text-slate-400">No references for the current selection.</div> : <div className="flex h-[174px] gap-3 overflow-x-auto p-3">{turn.references.map((reference, index) => { const selected = selectedReferenceId === reference.id; const linkedSteps = turn.trace.filter((step) => step.referenceIds?.includes(reference.id)).length; return <button data-reference-id={reference.id} key={reference.id} type="button" onClick={() => onSelectReference(reference.id)} className={`h-full w-[288px] shrink-0 overflow-hidden rounded-md border p-3 text-left transition ${selected ? "border-amber-500 bg-amber-50 shadow-sm ring-1 ring-amber-200" : "border-slate-200 bg-slate-50 hover:border-slate-400"}`}><div className="flex items-start gap-2"><span className="flex h-5 w-5 shrink-0 items-center justify-center rounded bg-slate-800 text-[8px] font-bold text-white">{index + 1}</span><div className="min-w-0"><div className="truncate text-[10px] font-bold text-slate-900">{reference.title}</div><div className="mt-0.5 text-[8px] font-semibold uppercase text-slate-400">{reference.type}{reference.version ? ` · ${reference.version}` : ""}{reference.sourceSystem ? ` · ${reference.sourceSystem}` : ""}</div><div className="mt-1 flex gap-1">{reference.sourcePage ? <span className="rounded bg-emerald-50 px-1.5 py-0.5 text-[7px] font-bold text-emerald-700">Source available · {reference.sourcePage}</span> : null}{reference.sourceViews?.[0] ? <span className="rounded bg-slate-100 px-1.5 py-0.5 text-[7px] font-bold text-slate-500">{reference.sourceViews[0]}</span> : null}</div></div></div><p className="mt-2 line-clamp-2 text-[9px] font-medium leading-3.5 text-slate-600">{reference.evidenceText}</p><div className="mt-2 border-t border-slate-200 pt-1.5 text-[8px] leading-3 text-slate-500"><span className="font-bold text-slate-700">Supports:</span> {reference.supports}</div><div className="mt-1.5 flex items-center gap-1 text-[8px] font-semibold text-slate-400"><Link2 className="h-2.5 w-2.5" />{linkedSteps} trace steps · {reference.linkedObjectIds.map((id) => objectById.get(id)?.label).filter(Boolean).slice(0, 2).join(", ")}</div></button>; })}</div>}
    </section>
  );
}
