export const ontologyClassCurieByViewType: Record<string, string> = {
  Product: "mfg:Product",
  Material: "mfg:Material",
  Component: "mfg:Material",
  Operation: "mfg:Operation",
  "Process Route": "core:Process",
  "Finished Product": "mfg:Product",
  Machine: "mfg:Machine",
  Fixture: "mfg:ManufacturingResource",
  Program: "mfg:ProcessParameter",
  "Engineering Spec": "core:Document",
  Document: "core:Document",
  "Quality Characteristic": "qual:QualityCharacteristic",
  "Inspection Method": "qual:InspectionMethod",
  "Control Method": "qual:InspectionMethod",
  "PFMEA Risk": "app:QualityRisk",
  "Control Plan Item": "qual:ControlPlanVersion",
  Supplier: "core:Agent",
  Customer: "core:Agent",
  "Process Box": "mfg:Operation",
  "Inventory Buffer": "mfg:Material",
  "WIP Buffer": "mfg:Material",
  "Finished Goods Inventory": "mfg:Material",
  "Value Stream Metric": "mfg:ProcessParameter",
  "Source System Mapping": "core:SourceSystem",
  Version: "core:VersionedEntity",
  Owner: "core:Agent",
};

export const ontologyRelationCurieByViewLink: Record<string, string> = {
  "link-product-requires-operation": "mfg:requiresOperation",
  "link-product-has-route": "mfg:flowsTo",
  "link-route-contains-operation": "mfg:flowsTo",
  "link-operation-consumes-material": "mfg:flowsTo",
  "link-operation-consumes-component": "mfg:flowsTo",
  "link-operation-precedes-operation": "mfg:flowsTo",
  "link-operation-produces-product": "mfg:produces",
  "link-operation-conducted-by-machine": "mfg:executedBy",
  "link-operation-requires-fixture": "mfg:flowsTo",
  "link-operation-uses-program": "mfg:usesParameter",
  "link-operation-defined-by-spec": "mfg:flowsTo",
  "link-program-runs-on-machine": "mfg:flowsTo",
  "link-fixture-mounted-on-machine": "mfg:flowsTo",
  "link-operation-controls-quality": "qual:controlsCharacteristic",
  "link-quality-inspected-by-method": "mfg:flowsTo",
  "link-quality-controlled-by-method": "mfg:flowsTo",
  "link-quality-referenced-by-control-plan": "mfg:flowsTo",
  "link-operation-has-risk": "mfg:flowsTo",
  "link-risk-mitigated-by-control": "mfg:flowsTo",
  "link-risk-linked-to-quality": "mfg:flowsTo",
  "link-document-describes-operation": "mfg:flowsTo",
  "link-document-governs-product": "mfg:flowsTo",
  "link-document-supports-spec": "mfg:flowsTo",
  "link-supplier-feeds-inventory": "mfg:flowsTo",
  "link-inventory-feeds-operation": "mfg:flowsTo",
  "link-operation-outputs-wip": "mfg:produces",
  "link-wip-feeds-operation": "mfg:flowsTo",
  "link-operation-outputs-fg": "mfg:produces",
  "link-fg-supplies-customer": "mfg:flowsTo",
  "link-vsm-metric-measures-operation": "mfg:flowsTo",
  "link-object-mapped-to-source": "core:hasSource",
};

export const ontologyViewConfigVersion = "1.0.0";
