from __future__ import annotations

import json
from pathlib import Path

from common import ROOT


def main() -> int:
    catalog = json.loads((ROOT / "ontology" / "catalog" / "ontology-catalog.json").read_text())
    lines = ["# Generated Knowledge Asset Inventory", "", f"Ontology version: `{catalog['ontologyVersion']}`", "", "## Modules", ""]
    lines.extend(f"- `{module['id']}`: `{module['file']}`" for module in catalog["modules"])
    lines.extend(["", "This file is generated by `python3 scripts/generate_docs.py`.", ""])
    output = ROOT / "docs" / "generated-asset-inventory.md"
    output.write_text("\n".join(lines))
    print(f"Generated {output.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
